# Generated by Django 4.2.4 on 2023-12-18 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sumo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('fight_rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('challenging_sumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenging_sumo', to='Sumo.sumo')),
                ('opponent_sumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_sumo', to='Sumo.sumo')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='Sumo.sumo')),
            ],
        ),
    ]
