# Generated by Django 4.2.4 on 2023-12-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sumo', '0001_initial'),
        ('Fight', '0003_alter_fight_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='challenging_sumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenging_sumo', related_query_name='challenging_sumo_fight', to='Sumo.sumo'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='opponent_sumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_sumo', related_query_name='opponent_sumo_fight', to='Sumo.sumo'),
        ),
    ]
