#The command to run this is 'kubectl apply -f backend.yaml'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: kube1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: ghcr.io/expruc/kubernetes-graduation-drill/k8s-final-drill:backend
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap