version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    networks:
      - ziv-network
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: users
    ports:
      - "3306:3306"
    networks:
      - ziv-network
    restart: always

networks:
  ziv-network:
