apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: kube1
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
