apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: kube1
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080