#Access the website with 'minikube service node-service -n kube1'
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: kube1
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8082 
      targetPort: 8080