# Generated by Django 4.2.4 on 2023-10-15 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attack_priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('enemy_organization', models.CharField(max_length=100)),
                ('target_goal', models.CharField(max_length=100)),
                ('was_target_destroyed', models.BooleanField(default=False)),
                ('target_id', models.CharField(editable=False, max_length=4, unique=True)),
            ],
        ),
    ]
