# Generated by Django 4.2.4 on 2023-12-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fight', '0001_initial'),
        ('Sumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('assumed_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assumed_winner', to='Sumo.sumo')),
                ('fight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_id', to='Fight.fight')),
            ],
        ),
    ]
