# Generated by Django 4.2.4 on 2023-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateTimeField(null=True)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
