# Generated by Django 4.2.4 on 2023-12-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sumo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sumo',
            name='last_name',
        ),
        migrations.AddField(
            model_name='sumo',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
